include:
  - project: 'wisdom-oss/ci-cd'
    ref: main
    file: '/documentation.yml'
  - project: 'wisdom-oss/ci-cd'
    ref: main
    file: '/service-update.yml'

stages:
  - update
  - docs

variables:
  COMPOSE_SERVICE_NAME: "service-water-usage-forecasts-rest"